let words = [
  { word: "JavaScript", hint: "The language that loves to surprise you 😄" },
  { word: "PHP", hint: "The duct tape of the internet 🎉" },
  { word: "Python", hint: "So laid-back, it's practically horizontal 🐍" },
  {
    word: "Java",
    hint: "Been around longer than your grandma's recipe book 📚",
  },
  { word: "C++", hint: "As subtle as a sledgehammer 💥" },
  { word: "Ruby", hint: "Beautiful, but high-maintenance 💎" },
  { word: "Swift", hint: "So fast, it'll leave you in the dust 🚀" },
  { word: "Go", hint: "Simple and satisfying, like a cheese sandwich 🧀" },
  { word: "Rust", hint: "Tough, resilient, and not afraid to get dirty 🛠️" },
  { word: "Haskell", hint: "Misunderstood by many, revered by few 🤔" },
  { word: "Perl", hint: "Eccentric and unpredictable 🌀" },
  { word: "Scala", hint: "Always striving for greatness 🏆" },
  { word: "Kotlin", hint: "Versatile and handy 🛠️" },
  { word: "Clojure", hint: "Mysterious and exclusive 🔮" },
  { word: "Elixir", hint: "Magical and potent ✨" },
  { word: "TypeScript", hint: "Always telling you what to do 🤖" },
  { word: "Dart", hint: "Tearing down the highway of code 🛣️" },
  { word: "R", hint: "Always digging through the data 🔍" },
  { word: "Lua", hint: "Flipping and twisting through the air ↩️" },
  { word: "Assembly", hint: "Living off the land of raw machine code ⚙️" },
];
